name: trtc_demo
description: TRTC Demo.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  tencent_trtc_cloud: ^0.2.1
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  crypto: ^3.0.1
  toast: ^0.1.5
  dio: ^4.0.0
  permission_handler: 5.0.1+1
  replay_kit_launcher: ^0.2.0+1
  flutter_launcher_icons: ^0.9.0
  fluro: ^2.0.3
  flutter_screenutil: ^5.0.0
  flutter_easyrefresh: ^2.2.0
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  flutter_easyloading: ^3.0.0
  common_utils: ^2.0.2
  chewie: ^1.0.0
  video_player: ^2.1.1
  fijkplayer: ^0.8.7
  tapped: any
  safemap: any
  wakelock: ^0.4.0
  jmessage_flutter: 2.0.3
  fluttertoast: ^8.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: images/icon.png

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/icon.png
   - assets/images/

version: 1.2.0
